version: '2'

networks:
   fabric-host4:
services:
   peer2-org1:
      container_name: peer2-org1.inuit.local
      image: hyperledger/fabric-peer
      environment:
         - CORE_PEER_ID=peer2-org1.inuit.local
         - CORE_PEER_ADDRESS=peer2-org1.inuit.local:7051
         - CORE_PEER_LOCALMSPID=org1MSP
         - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org1/peer2/msp
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-host4
         - FABRIC_LOGGING_SPEC=grpc=debug
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org1/peer2/tls-msp/signcerts/cert.pem
         - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org1/peer2/tls-msp/keystore/key.pem
         - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org1/peer2/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - CORE_PEER_GOSSIP_USELEADERELECTION=true
         - CORE_PEER_GOSSIP_ORGLEADER=false
         - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org1.inuit.local:7051
         - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
         - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org1.inuit.local:7051
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
      volumes:
         - /var/run:/host/var/run
         - /tmp/hyperledger/org1/peer2:/tmp/hyperledger/org1/peer2
      extra_hosts:
         - "peer1-org1.inuit.local:192.168.176.103"
         - "ord1-org0.inuit.local:192.168.176.103"
         - "cli-org1.inuit.local:192.168.176.103"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "rca-org1.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "ca-tls.inuit.local:192.168.176.101"
      networks:
         - fabric-host4
      ports:
         - 8051:7051
         - 8053:7053

   peer2-org2:
      container_name: peer2-org2.inuit.local
      image: hyperledger/fabric-peer
      environment:
         - CORE_PEER_ID=peer2-org2.inuit.local
         - CORE_PEER_ADDRESS=peer2-org2.inuit.local:7051
         - CORE_PEER_LOCALMSPID=org2MSP
         - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2/peer2/msp
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-host4
         - FABRIC_LOGGING_SPEC=debug
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2/peer2/tls-msp/signcerts/cert.pem
         - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2/peer2/tls-msp/keystore/key.pem
         - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2/peer2/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - CORE_PEER_GOSSIP_USELEADERELECTION=true
         - CORE_PEER_GOSSIP_ORGLEADER=false
         - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org2.inuit.local:7051
         - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
         - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2.inuit.local:10051
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer2
      extra_hosts:
         - "peer1-org1.inuit.local:192.168.176.103"
         - "ord1-org0.inuit.local:192.168.176.103"
         - "cli-org1.inuit.local:192.168.176.103"
         - "peer1-org2.inuit.local:192.168.176.105"
         - "cli-org2.inuit.local:192.168.176.105"
         - "rca-org2.inuit.local:192.168.176.105"
         - "rca-org1.inuit.local:192.168.176.101"
         - "rca-org0.inuit.local:192.168.176.101"
         - "ca-tls.inuit.local:192.168.176.101"   
      volumes:
         - /var/run:/host/var/run
         - /tmp/hyperledger/org2/peer2:/tmp/hyperledger/org2/peer2
      networks:
         - fabric-host4
      ports:
         - 9051:7051
         - 9053:7053
                                                                     
