version: '2'

networks:
   fabric-host5:

services:
   rca-org2:
      container_name: rca-org2.inuit.local
      image: hyperledger/fabric-ca
      command: sh -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw --port 7055'
      environment:
         - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-org2-rca/crypto
         - FABRIC_CA_SERVER_NAME=rca-org2.inuit.local
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CSR_CN=rca-org2.inuit.local
         - FABRIC_CA_SERVER_CSR_HOSTS=rca-org2.inuit.local,localhost,0.0.0.0
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - /tmp/hyperledger/org2/ca:/tmp/hyperledger/fabric-org2-rca
      networks:
         - fabric-host5
      ports:
         - 7055:7055

   peer1-org2:
      container_name: peer1-org2.inuit.local
      image: hyperledger/fabric-peer
      environment:
         - CORE_PEER_ID=peer1-org2.inuit.local
         - CORE_PEER_ADDRESS=peer1-org2.inuit.local:7051
         - CORE_PEER_LOCALMSPID=org2MSP
         - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2/peer1/msp
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-host5
         - FABRIC_LOGGING_SPEC=debug
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2/peer1/tls-msp/signcerts/cert.pem
         - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2/peer1/tls-msp/keystore/key.pem
         - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2/peer1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - CORE_PEER_GOSSIP_USELEADERELECTION=true
         - CORE_PEER_GOSSIP_ORGLEADER=false
         - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2.inuit.local:7051
         - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer1
      volumes:
         - /var/run:/host/var/run
         - /tmp/hyperledger/org2/peer1:/tmp/hyperledger/org2/peer1
      extra_hosts:
         - "peer1-org1.inuit.local:192.168.176.103"
         - "ord1-org0.inuit.local:192.168.176.103"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"
      networks:
         - fabric-host5
      ports:
         - 10051:7051
         - 10053:7053

   cli-org2:
      container_name: cli-org2.inuit.local
      image: hyperledger/fabric-tools
      tty: true
      stdin_open: true
      environment:
         - GOPATH=/opt/gopath
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - FABRIC_LOGGING_SPEC=DEBUG
         - CORE_PEER_ID=cli-org2.inuit.local
         - CORE_PEER_ADDRESS=peer1-org2.inuit.local:10051
         - CORE_PEER_LOCALMSPID=org2MSP
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2/peer1/tls-msp/tlscacerts/tls-ca-tls-inuit-local-7052.pem
         - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2/peer1/msp
         - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2
      command: sh
      volumes:
         - /tmp/hyperledger/org2/peer1:/tmp/hyperledger/org2/peer1
         - /tmp/hyperledger/org1/peer1/assets/chaincode:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
         - /tmp/hyperledger/org2/admin:/tmp/hyperledger/org2/admin
      extra_hosts:
         - "peer1-org1.inuit.local:192.168.176.103"
         - "ord1-org0.inuit.local:192.168.176.103"
         - "peer2-org1.inuit.local:192.168.176.104"
         - "peer2-org2.inuit.local:192.168.176.104"        
      networks:
         - fabric-host5

