version: '2'

networks:
   fabric-ca:

services:
   ca-tls:
      container_name: ca-tls.inuit.local
      image: hyperledger/fabric-ca
      environment:
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-tls
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CSR_CN=ca-tls.inuit.local
         - FABRIC_CA_SERVER_DEBUG=true
         - FABRIC_CA_SERVER_CSR_HOSTS=ca-tls.inuit.local
      command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
      volumes:
         - /etc/hyperledger/fabric-ca-tls:/etc/hyperledger/fabric-ca-tls
      networks:
         - fabric-ca
      ports:
         - 7052:7052
